version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres-server

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

    volumes:
      - postgres-data:/var/lib/postgres-data

volumes:
  postgres-data: